const garments = [
  {
    id: '1',
    image: '/images/bluejumper.jpg',
    imgAltText: 'blue jumper',
    size: 'XS',
    color: 'navy',
    material: 'cotton',
    brand: '&other stories',
  },
  {
    id: '2',
    image: '/images/blueskirt.jpg',
    imgAltText: 'blue skirt',
    size: '164',
    color: 'navy',
    material: 'cotton',
    brand: 'Tommy Hilfiger',
  },
  {
    id: '3',
    image: '/images/stripedshirt.jpg',
    imgAltText: 'striped shirt',
    size: '34',
    color: 'lightblue',
    material: 'cotton',
    brand: 'Ralph Lauren',
  },
  {
    id: '4',
    image: '/images/whitetop.jpg',
    imgAltText: 'white top',
    size: 'XS',
    color: 'white',
    material: 'cotton',
    brand: 'H&M',
  },
  {
    id: '5',
    image: '/images/reddress.jpg',
    imgAltText: 'red dress',
    size: '164',
    color: 'red',
    material: 'cotton',
    brand: 'H&M',
  },
  {
    id: '6',
    image: '/images/beigeblazer.jpg',
    imgAltText: 'beige blazer',
    size: 'XS',
    color: 'beige',
    material: 'cotton',
    brand: 'Zara',
  },
  {
    id: '7',
    image: '/images/yellowskirt.jpg',
    imgAltText: 'yellow skirt',
    size: 'XS',
    color: 'yellow',
    material: 'cotton',
    brand: 'Ralph Lauren',
  },
  {
    id: '8',
    image: '/images/beigetrousers.jpg',
    imgAltText: 'beige trousers',
    size: 'XS',
    color: 'beige',
    material: 'cotton',
    brand: 'H&M',
  },
];

export default garments;
